version: '3.2'

services:
  slackbot:
    build: .
    ports: 
      - "3000:3000"
    env_file:
      - ./.env

  ngrok:
    image: wernight/ngrok
    depends_on: 
      - slackbot
    ports: 
      - "4040:4040"
    environment:
      - NGROK_AUTH=${NGROK_AUTH}
      - NGROK_PORT=${NGROK_PORT}
      - NGROK_REGION=${NGROK_REGION}
